/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eetrust_securedocsdk_CryptoUtil */

#ifndef _Included_com_eetrust_securedocsdk_CryptoUtil
#define _Included_com_eetrust_securedocsdk_CryptoUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eetrust_securedocsdk_CryptoUtil
 * Method:    EncryptFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;JJILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eetrust_securedocsdk_CryptoUtil_EncryptFile
  (JNIEnv *, jobject, jstring, jstring, jlong, jlong, jint, jstring);

/*
 * Class:     com_eetrust_securedocsdk_CryptoUtil
 * Method:    DecryptFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eetrust_securedocsdk_CryptoUtil_DecryptFile
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_eetrust_securedocsdk_CryptoUtil
 * Method:    isSecureDoc
 * Signature: (Ljava/lang/String;)Lcom/eetrust/bean/IsSecureDocBean2;
 */
JNIEXPORT jobject JNICALL Java_com_eetrust_securedocsdk_CryptoUtil_isSecureDoc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eetrust_securedocsdk_CryptoUtil
 * Method:    getSecureDocInfo
 * Signature: (Ljava/lang/String;)Lcom/eetrust/securedocsdk/TestBean;
 */
JNIEXPORT jobject JNICALL Java_com_eetrust_securedocsdk_CryptoUtil_getSecureDocInfo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
