package com.eetrust.bean;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "USER_LOG".
 */

public class UserLog {

    private Long id;
    private long archivesID;
    private long docID;
    private Integer oper;
    private Integer online;
    private Integer result;
    private String memo;
    private String clientIP;
    private String opertime;
    private String LoginName;



    public UserLog() {
    }

    public UserLog(Long id) {
        this.id = id;
    }

    public UserLog(Long id, long archivesID, long docID, Integer oper, Integer online, Integer result, String memo, String clientIP, String opertime) {
        this.id = id;
        this.archivesID = archivesID;
        this.docID = docID;
        this.oper = oper;
        this.online = online;
        this.result = result;
        this.memo = memo;
        this.clientIP = clientIP;
        this.opertime = opertime;
        this.LoginName = LoginName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getArchivesID() {
        return archivesID;
    }

    public void setArchivesID(long archivesID) {
        this.archivesID = archivesID;
    }

    public long getDocID() {
        return docID;
    }

    public void setDocID(long docID) {
        this.docID = docID;
    }

    public Integer getOper() {
        return oper;
    }

    public void setOper(Integer oper) {
        this.oper = oper;
    }

    public Integer getOnline() {
        return online;
    }

    public void setOnline(Integer online) {
        this.online = online;
    }

    public Integer getResult() {
        return result;
    }

    public void setResult(Integer result) {
        this.result = result;
    }

    public String getMemo() {
        return memo;
    }

    public void setMemo(String memo) {
        this.memo = memo;
    }

    public String getClientIP() {
        return clientIP;
    }

    public void setClientIP(String clientIP) {
        this.clientIP = clientIP;
    }

    public String getOpertime() {
        return opertime;
    }

    public void setOpertime(String opertime) {
        this.opertime = opertime;
    }


    public String getLoginName() {
        return LoginName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLoginName( String LoginName) {
        this.LoginName = LoginName;
    }

}
